[package]
name = "normal-rust-task-manager-lol" 
version = "0.1.0"
edition = "2021"
authors = ["v1peridae"]
description = "A normal command-line task manager"
license = "ISC"
repository = "https://github.com/v1peridae/loulearnsrust-"
keywords = ["cli", "task-manager"]

[dependencies]
